#!/bin/bash

> ~/.calendar
google calendar list --date `date +%F` --cal ".oug.*" --fields title,when | egrep -v '^\[|^$' | while read line
do
    current_time=$(date +%H%M)
    event=$(echo "$line"|cut -d, -f1)
    time=$(echo "$line"|cut -d, -f2)
    start_time=$(echo "$time"|awk '{print $3}')
    start_time_compact=$(echo "$start_time"|tr -d :)
    end_time=$(echo "$time"|awk '{print $7}')

    if [ $start_time_compact -lt $current_time ] ; then
        continue
    else
        echo "$event -- $start_time - $end_time" >> ~/.calendar
    fi
done

